os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: hOnbSm+tsFLrv7SJUnVXv2bksHR1FWdwVj8EH84c4URR6zA6um3FjQ8mJL7abPpT/wnaak9eNLV+vgRFJOUYNyYkfhfLX6LNzQfGfkdYSnbBpL4l6otZGqjO35urd6V58G+MTDED4AhLb4tCOo/CMGh1KHNjC2ZFIz3XXzX994XRyz62pwp5BVFNZWPnCmgowDL6wuC9CVUqcyOGlGJAQnPw0Mi6zTtCrFiWxerJQe0NVqmL8dOexwl4maUARHhNb0NV1wW2Z4FESLlcCX9yHezKcDP0Kl4SAuYvuODPK5QYusvw9MbSR9n8CuglFMHElrBC/vzhHIAzNzndnzK5ykgKUDe+RCkSUOpRoxH8zer29s/gFR1w5vFqUeMfwreHvViuIIdPAliSKfl9o3DY8FlX50N8dsbR+JAEO6wkV/egG5NRbiXKzQl2tAzubHNx5Y21PDcUxVkem+Syfux1JkxynmoTEoCnoSS+qYPIvm0jJyK9N6SeF0zbxbhwwSCyRwi1wjkuebWIQ1D4nbXFyr/XVm8Ixj2QxZDN9VT1uxXwDIj9WR/sulC9fxJYNHzpNM4/Gcm1Ny7uzsTGM4jB0z3JMEQLYW37llIZHckAC2G8ggsQQj+8CiPpFrZWsI0hWCF/qUlq8COKJS5yUp/WfPeuJUh4oLhoYEQilrWwy20=
