os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8

cache:
  directories:
    - '~/.m2/repository'

before_install:
- bash .util/build_xatkit.sh
  
script:
- mvn install

